apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yaml: |
    name: {{ .Values.config.name }}
    description: {{ .Values.config.description }}
    urls:
      {{- range .Values.config.urls }}
      - {{ . | quote }}
      {{- end }}