{
 "title": "external url monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": " https://httpstat.us/200 uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sample_external_url_up{url=\"https://httpstat.us/200\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": " https://httpstat.us/503 uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sample_external_url_up{url=\"https://httpstat.us/503\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "https://httpstat.us/503 status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sample_external_url_up{url=\"https://httpstat.us/503\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "https://httpstat.us/200 status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sample_external_url_up{url=\"https://httpstat.us/200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "https://httpstat.us/503 response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(sample_external_url_response_ms_sum{url=\"https://httpstat.us/503\"}[1m])",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "https://httpstat.us/200 response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(sample_external_url_response_ms_sum{url=\"https://httpstat.us/200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}